# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openmidas.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fopenmidas.proto\x12\topenmidas\")\n\x06\x45xtras\x12\r\n\x05model\x18\x01 \x01(\t\x12\x10\n\x08\x63olormap\x18\x02 \x01(\x05\x42\x1e\n\x14\x65\x64u.cmu.cs.openmidasB\x06Protosb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openmidas_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024edu.cmu.cs.openmidasB\006Protos'
  _EXTRAS._serialized_start=30
  _EXTRAS._serialized_end=71
# @@protoc_insertion_point(module_scope)
