# The environment variables such as 
# ${FACE_THRESHOLD} and ${API_KEY} should
# reside in a .env file along side docker-compose.yaml
#
# To speed up build when buildkit is not yet enabled by default,
# COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build

version: '2.3'
services:
  gabriel-server:
    #image: cmusatyalab/openmidas:${TAG}
    build: .
    container_name: gabriel-server
    ports:
      - "9099:9099"
      - "5555:5555"
    entrypoint: ["openmidas"]
    restart: unless-stopped
    networks:
      - openmidas-net

  http-server:
    image: httpd:2.4
    container_name: http-server
    ports:
      - "${HTTP_PORT}:80"
    restart: unless-stopped
    networks:
      - openmidas-net
    volumes:
      - ./images-vol:/usr/local/apache2/htdocs
  
  midas-engine:
    #image: cmusatyalab/openmidas:${TAG}
    build: .
    container_name: midas-engine
    restart: unless-stopped
    privileged: true
    entrypoint: ["openmidas-midas-engine", "--model", "${DNN}", "${STORE}"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./models:/root/.cache/torch/hub/
      - ./images-vol:/openmidas-server/images/
    depends_on:
      - gabriel-server
    networks:
      - openmidas-net
    environment:
       - WEBSERVER=${WEBSERVER_URL}:${HTTP_PORT}
    #  - TF_FORCE_GPU_ALLOW_GROWTH=true #the following environment variable may be necessary if your GPU only has a modest (~2GB) amount of RAM
    #  - CUDA_VISIBLE_DEVICES=-1 #set this if you want to force CPU only

networks:
  openmidas-net:



